all:
  children:
    identity_data:
      hosts:
        server1.example.com:
      vars:
        ansible_user: app
        pillars: [authentication, authorization, compliance, finance, storage, communication]
    workflow_ops:
      hosts:
        server2.example.com:
      vars:
        ansible_user: app
        pillars: [workflow, lifecycle]
