// GENERATED by infra/build/generator.py — do not edit; regenerate after
// changing the declarative tree (infra/instances/dev/).
import type { DynamicIconNameType } from "@/types"

export type GeneratedApp = {
  title: string
  href: string
  iconName: DynamicIconNameType
  section: string
}

export const generatedApps: GeneratedApp[] = [
  {
    title: "Databases",
    href: "https://nocodb.irl.coop",
    iconName: "Database",
    section: "Coop",
  },
  {
    title: "Surveys",
    href: "https://forms.irl.coop",
    iconName: "ClipboardList",
    section: "Coop",
  },
  {
    title: "Events",
    href: "https://events.irl.coop",
    iconName: "CalendarDays",
    section: "Coop",
  },
  {
    title: "Studio",
    href: "https://studio.irl.coop",
    iconName: "Palette",
    section: "Build",
  },
  {
    title: "Social Media",
    href: "/apps/social-media",
    iconName: "Megaphone",
    section: "Coop",
  },
  {
    title: "API",
    href: "https://api.irl.coop",
    iconName: "Braces",
    section: "Build",
  },
  {
    title: "Live Video",
    href: "/apps/stream",
    iconName: "Video",
    section: "Coop",
  },
  {
    title: "Accounting",
    href: "https://accounting.irl.coop",
    iconName: "Calculator",
    section: "Coop",
  },
]
