import type { NavigationType } from "@/types"
import { generatedApps } from "@/data/apps.generated"

// Side navigation organized by member personas:
//   Coop           — the daily workspace every member reaches for
//   Administration — the coop's operators: nodes, people, money
//   Account        — personal settings
//   Build          — the developers connecting to the API
// Internal dashboard routes live here. External services (Databases, API,
// Studio, Postiz, Owncast, …) are GENERATED from the declarative stack —
// apps.generated.ts, regenerated by infra/build/generator.py — and merged into
// their section below by each app spec's `nav.section`.
const sections: NavigationType[] = [
  {
    title: "Coop",
    items: [
      {
        title: "Home",
        href: "/dashboards/overview",
        iconName: "LayoutDashboard",
      },
      {
        title: "Projects",
        href: "/apps/projects",
        iconName: "FolderKanban",
      },
      {
        title: "Groups",
        href: "/apps/groups",
        iconName: "Network",
      },
      {
        title: "Webmail",
        href: "/apps/webmail",
        iconName: "Mail",
      },
      {
        title: "Calls",
        href: "/apps/calls",
        iconName: "Phone",
      },
      {
        title: "Files",
        href: "/apps/files",
        iconName: "FolderOpen",
      },
      {
        title: "Documents",
        href: "/apps/docs",
        iconName: "FileText",
      },
    ],
  },
  {
    title: "Administration",
    items: [
      {
        title: "Shard Nodes",
        href: "/dashboards/analytics",
        iconName: "Server",
      },
      {
        title: "Members",
        href: "/dashboards/crm",
        iconName: "Users",
      },
      {
        title: "Safes",
        href: "/dashboards/ecommerce",
        iconName: "Wallet",
      },
    ],
  },
  {
    title: "Account",
    items: [
      {
        title: "Profile",
        href: "/pages/account/profile",
        iconName: "User",
      },
      {
        title: "Settings",
        href: "/pages/account/settings",
        iconName: "UserCog",
      },
    ],
  },
  {
    title: "Build",
    items: [],
  },
]

// Merge the generated external apps into their section (appended, in
// declaration order). A `nav.section` that matches no section above is skipped.
for (const app of generatedApps) {
  const section = sections.find((s) => s.title === app.section)
  if (section) {
    section.items.push({
      title: app.title,
      href: app.href,
      iconName: app.iconName,
    })
  }
}

export const navigationsData: NavigationType[] = sections.filter(
  (s) => s.items.length > 0,
)
