# coturn for irl.coop — TURN/STUN relay for Element Call.
# REST auth secret shared with the Synapse homeserver (gitignored).
listening-port=3478
tls-listening-port=5349
realm=irl.coop
external-ip=64.135.141.73/192.168.18.20
relay-device=eth0
min-port=49152
max-port=65535
use-auth-secret
# static-auth-secret=b2340edfc14217e761cdd541d932bb787d173ade0b12e8ab944832f1f6e8f411
user-quota=12
total-quota=1200
no-cli
no-tlsv1
no-tlsv1_1
no-tlsv1_2
log-file=stdout
