services:
  temporal:
    image: temporalio/server:1.24.0
    environment:
      - DB=postgresql
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=postgres # connect to Citus

  formbricks:
    image: formbricks/formbricks:latest
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:***@postgres:5432/formbricks
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forms.rule=Host(`forms.${DOMAIN}`)"

  webstudio:
    image: webstudio/webstudio:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.studio.rule=Host(`studio.${DOMAIN}`)"
